package com.danunant.bbank.vm

import androidx.lifecycle.ViewModel
import androidx.lifecycle.viewModelScope
import com.danunant.bbank.data.Account
import com.danunant.bbank.data.AccountType
import com.danunant.bbank.data.BbankRepository
import com.danunant.bbank.data.TransferResult
import com.danunant.bbank.data.Txn
import com.danunant.bbank.data.User
import dagger.hilt.android.lifecycle.HiltViewModel
import kotlinx.coroutines.flow.MutableStateFlow
import kotlinx.coroutines.flow.StateFlow
import kotlinx.coroutines.launch
import java.util.UUID
import javax.inject.Inject

@HiltViewModel
class BankViewModel @Inject constructor(
    private val repository: BbankRepository // Only inject Repository
) : ViewModel() {

    val currentUser: StateFlow<User?> = repository.currentUser
    val accounts: StateFlow<List<Account>> = repository.accounts
    val txns: StateFlow<List<Txn>> = repository.txns

    private val _transferResult = MutableStateFlow<TransferResult?>(null)
    val transferResult: StateFlow<TransferResult?> = _transferResult

    private val _isLogoutDialogVisible = MutableStateFlow(false)
    val isLogoutDialogVisible: StateFlow<Boolean> = _isLogoutDialogVisible

    // --- State for the account-specific delete dialog ---
    private val _accountToDelete = MutableStateFlow<Account?>(null)
    val accountToDelete: StateFlow<Account?> = _accountToDelete


    fun showLogoutDialog() {
        _isLogoutDialogVisible.value = true
    }

    fun dismissLogoutDialog() {
        _isLogoutDialogVisible.value = false
    }

    fun logout() {
        viewModelScope.launch {
            repository.logout()
            dismissLogoutDialog()
        }
    }

    fun onTransfer(fromId: String, toAccountNumber: String, amountSatang: Long, desc: String) {
        viewModelScope.launch {
            if (currentUser.value == null) return@launch
            val token = UUID.randomUUID().toString()
            // Call repository's suspend function
            _transferResult.value = repository.transfer(token, fromId, toAccountNumber, amountSatang, desc)
        }
    }

    fun clearTransferResult() {
        _transferResult.value = null
    }


    fun onAccountDeleteRequest(account: Account) {
        _accountToDelete.value = account
    }

    fun onAccountDeleteConfirm() {
        _accountToDelete.value?.let { account ->
            viewModelScope.launch {
                // Call repository
                repository.deleteAccount(account.id)
                _accountToDelete.value = null
            }
        }
    }

    fun onAccountDeleteDismiss() {
        _accountToDelete.value = null
    }

    // This function is still needed for UpsertAccountScreen to fetch existing data
    suspend fun getAccountById(id: String): Account? {
        // Call repository
        return repository.getAccountById(id)
    }

    // --- THIS IS THE CORRECT saveAccount FUNCTION ---
    // It takes only necessary UI data and calls the repository
    fun saveAccount(id: String?, name: String, type: AccountType) {
        viewModelScope.launch {
            val ownerId = currentUser.value?.id ?: return@launch
            val accountToSave = if (id == null) {
                // Create NEW account object (number will be generated by repo)
                Account(
                    id = UUID.randomUUID().toString(), // Generate new local ID
                    ownerId = ownerId,
                    name = name,
                    type = type,
                    number = "", // Repo will generate this
                    balanceSatang = 0
                )
            } else {
                // Get EXISTING account data from repo to update it
                val existing = repository.getAccountById(id) ?: return@launch
                existing.copy(name = name, type = type) // Only update name and type
            }
            // Call repository to handle saving (and number generation if new)
            repository.saveAccount(accountToSave)
        }
    }
    // --- END CORRECTION ---

}